### ISSUE TITLE
Unable to run image

### ISSUE THREAD

**Issue by xadamxk** [StephaneTurquay/metabase-arm64-docker#4]
I am using a MacBook Pro M3 with Rancher desktop.
When I use the provided example (pointing to a local db):

```
services:
  metabase:
    image: stephaneturquay/metabase-arm64
    container_name: metabase
    restart: always
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      MB_DB_TYPE: "${DB_TYPE:-postgres}"
      MB_DB_DBNAME: "${DB_NAME:-metabase}"
      MB_DB_PORT: "${DB_PORT:-5432}"
      MB_DB_USER: "${DB_USER:-postgres}"
      MB_DB_PASS: "${DB_PASS:-postgres}"
      MB_DB_HOST: "${DB_HOST:-localhost}"
      MB_LOG_LEVEL: debug
      MB_JETTY_PORT: "${PORT:-4000}"
```

I get this warning when I run `docker compose up metabase -d`:
> ! metabase The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

And the only thing available in the docker logs are:
> [Too many errors, abort]

Do you have any recommendations on running this image? @StephaneTurquay
